### ISSUE TITLE
Accounts without email addresses

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/decision-records#3]
To create an account with the Cadasta platform, users currently need an email address. Since many of our partners work in areas with limited access to the Web, not all users of the platform will have an email address. 

This issue is to start a discussion to work out how we can support users without email addresses. 

### Facebook account

@wonderchook mentioned that many people have Facebook accounts. Users could use their Facebook account to sign in. We’re using django-allauth, which already provides means to enable login using social media accounts, including Facebook.

### Username only

Instead of requiring an email address to sign in, users could register and sign-in with their username. 

Some considerations:

- How do we verify these accounts? 
- Do we want to provide this option generally or restrict it to organisations or projects? Organisation admins/project managers could activate this option. 

### Managed accounts

An authorised user (organization admin, project manager) of the Cadasta platform creates accounts for community members. Users can sign-in using the username they have been given. 

Some considerations:

- Who gets permission to create user accounts?
- Will these persons be able to remove the user accounts as well?
- How will the password be set? Do we create a random password and prompt the user to change their password when they first login? 
- How do we let users know about their initial password?

**Comment by clash99** [comment]
For the managed accounts, we should also have an easy way to communicate to the managed user who is responsible for managing their account so they have a way to contact them.

**Comment by dpalomino** [comment]
Hi, thanks @oliverroick for raising this. Here my two cents: 

I agree that using Facebook accounts to sign in would be very useful. They are more popular than email addresses in many contexts. 

For the username-only accounts, I can only think in 2FA via SMS to verify those accounts or to reset the password. Or to allow them not to be verified. 

Regarding the managed accounts: 
- I think the organization admins could be the ones allowed to create user accounts. 
- I don't we need to cover the case of admins removing these accounts, as organizations admins can remove the user from the organization (and potentially that user could be part of other organization)
- Passwords: I would say that the person managing those accounts would be creating the password (a random generated one I think it would be too complicated). And communicating the password to the managed user could be tricky, as I think many of those users could not have mail addresses. I think the "manager" should communicate to the managed user both the username and the password. 
- I think most of these managed users will never access to the platform, but just they will be submitting information via mobile applications (surveyors). So asking the managed user to change the password after their first login might not be very effective.

**Comment by wonderchook** [comment]
What about allowing phone numbers? I think even more people are going to be likely to have a phone number (quite possibly all our users). We'd need to look into service options to facilitate that though.

**Comment by oliverroick** [comment]
Documenting another idea @amplifi @dpalomino and me discussed last week as basis for discussion next week:

## Context

Users currently need to register with an email address and confirm this email address via the link provided in a confirmation email. 

For some projects, project managers set up user accounts for data collectors (including their user name and password) and setup GeoODK on data collector’s phones with those credentials. Often data collectors do not have an email address. It is currently not possible to register these users on the platform. 

## Decision

We will introduce a new user account type for users who only collect data via GeoODK (I call these accounts _GeoODK user_ for now). 

### Register accounts without emails

Project managers create _GeoODK user_ accounts on behalf of the data collector. The accounts can be registered without an email address. As a GeoODK collector, users will be able to download forms to GeoODK and to upload data collected from their mobile phones. They will further be able to login to the platform to update their profile (username and password). All other views and actions will not be permitted. 

Project managers can chose to set an optional expiry date for these accounts. After that expiry date data collectors will not be able to download forms or upload data from and to the platform. Project managers can extend the expiry date via the platform.

(Should it be possible to create GeoODK collector accounts by providing an email address?)

### Resetting the password

(This area is not very well defined yet, needs more discussion/thinking. There are two options I can think of)

1. Send a code to a phone number, users enter the code and reset the password. 
2. Project managers can reset passwords for all _GeoODK users_ in their project. (The question is, do they have a phone number that they can use to register?)

### Promoting users

Project managers can promote users accounts to standard accounts. An email address must be provided to upgrade an account. A confirmation email is sent to the email address with a link to confirm the email address. Confirming the email address upgrades the account. If the email is not confirmed, the account will not be upgraded.

## Consequences

Project managers will be able to register users who do not have an email address for use with GeoODK.

**Comment by wonderchook** [comment]
What about instead letting people confirm their accounts by sms? I have worked with users that have computers and have no email address quite a few times. So I'm a bit worried the GeoODK account type will only fix part of the problem.

Since we are suggesting sending a code to a phone number anyway it seems like this would work.
